FROM python:3.9-slim-bullseye

RUN export DEBIAN_FRONTEND=noninteractive &&\
    echo "deb https://mirrors.tencent.com/debian/ bullseye main non-free contrib" >/etc/apt/sources.list && \
    echo "deb https://mirrors.tencent.com/debian-security/ bullseye-security main" >>/etc/apt/sources.list && \
    echo "deb https://mirrors.tencent.com/debian/ bullseye-updates main non-free contrib" >>/etc/apt/sources.list && \
    echo "deb https://mirrors.tencent.com/debian/ bullseye-backports main non-free contrib" >>/etc/apt/sources.list && \
    echo "deb-src https://mirrors.tencent.com/debian/ bullseye main non-free contrib" >>/etc/apt/sources.list && \
    echo "deb-src https://mirrors.tencent.com/debian-security/ bullseye-security main" >>/etc/apt/sources.list && \
    echo "deb-src https://mirrors.tencent.com/debian/ bullseye-backports main non-free contrib" >>/etc/apt/sources.list && \
    echo "deb-src https://mirrors.tencent.com/debian/ bullseye-updates main non-free contrib" >>/etc/apt/sources.list \
    && apt-get  update -y \
    && apt-get  install -y --no-install-recommends \
    git \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

ENV VENV="whisper"
ENV PATH="${PATH}:${VENV}/bin"

WORKDIR /app
COPY . /app

RUN python3 -m venv $VENV \
    && $VENV/bin/pip install --upgrade pip -i https://pypi.mirrors.ustc.edu.cn/simple \
    && $VENV/bin/pip install -U pip setuptools -i https://pypi.mirrors.ustc.edu.cn/simple \
    && $VENV/bin/pip install -r /app/requirements.txt -i https://pypi.mirrors.ustc.edu.cn/simple \
    && rm -rf ~/.cache/pip




ENTRYPOINT ["gunicorn", "--bind", "0.0.0.0:9000", "--workers", "1", "--timeout", "0", "backend.app:app", "-k", "uvicorn.workers.UvicornWorker"]