FROM python:3.11.1-slim

RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get -qq update \
    && apt-get -qq install --no-install-recommends \
    git \
    ffmpeg \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

ENV VENV="whisper"
ENV PATH="${PATH}:${VENV}/bin"

RUN python3 -m venv $VENV \
    && $VENV/bin/pip install -U pip setuptools -i https://pypi.tuna.tsinghua.edu.cn/simple \
    && $VENV/bin/pip install -r /app/requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

WORKDIR /app

COPY . /app


ENTRYPOINT ["gunicorn", "--bind", "0.0.0.0:9000", "--workers", "1", "--timeout", "0", "app.webservice:app", "-k", "uvicorn.workers.UvicornWorker"]